name: build

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '6.0.x' # The .NET SDK version to use

jobs:
  build:

    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore Código/Backend/PharmaGo.sln
      
    - name: Build
      run: dotnet build --configuration Release --no-restore Código/Backend/PharmaGo.sln

    - name: Run Unit Tests
      run: dotnet test Código/Backend/PharnaGo.Test/PharmaGo.Test.csproj
      
    
    - name: Install SpecFlow.Tools.MsBuild.Generation
      run: dotnet tool install --global SpecFlow.Tools.MsBuild.Generation

    - name: Generate SpecFlow files
      run: dotnet msbuild /t:SpecFlowGenerateAll C:\Users\Administrador\Desktop\obligatorio-lamanna-molinari-daners\Código\Backend\PharmaGo.sln

    - name: Run SpecFlow Tests
      run: dotnet test C:\Users\Administrador\Desktop\obligatorio-lamanna-molinari-daners\Código\Backend\PharmaGo.SpecFlow\PharmaGo.SpecFlow.csproj
